<?php


namespace Core\lib;


use Core\BeanFactory;
use Core\init\MyDB;
use Illuminate\Database\Eloquent\Model;

class BaseModel extends Model
{
    /**
     * 重新 laravel model 的代码，来支持 数据库链接池的操作
     */
    public function __call($method, $parameters)
    {
        return $this->invoke(function () use ($method, $parameters) {
            return parent::__call($method, $parameters);
        });
    }

    public function save(array $options = [])
    {
        return $this->invoke(function () use ($options) {
            parent::save($options);
        });
    }

    public function saveOrFail(array $options = [])
    {
        return $this->invoke(function () use ($options) {
            return parent::saveOrFail($options); // TODO: Change the autogenerated stub
        });
    }

    public function update(array $attributes = [], array $options = [])
    {
        return $this->invoke(function () use ($attributes, $options) {
            return parent::update($attributes, $options); // TODO: Change the autogenerated stub
        });

    }

    private function invoke(callable $function)
    {
        $myDB = clone BeanFactory::getBean(MyDB::class);
        $obj = $myDB->genConnection();
        try {
            return $function();
        } catch (\Exception $exception) {
            var_dump($exception);
            return null;
        } finally {
            $myDB->releaseConnection($obj);
        }
    }

}